### ISSUE TITLE
How to calculate the average execution cost?

### ISSUE THREAD

**Issue by qq592922218** [NarcissusHliangZhao/Implementation_of_MEC_papers#2]
How to calculate the average execution cost?

**Comment by NarcissusHliangZhao** [comment]
你好。
实际上，我并没有计算average execution cost。
LODCO算法（借助Lyapunov优化）已经将问题转变成了一个在每个time slot内的deterministic problem，没有再计算average execution cost的必要。
如果一定要计算该值，那就按照定义来就行了：借助我设置的中间变量cost来取时均值即可。

**Comment by qq592922218** [comment]
你好
我想知道你是怎么得到你论文中的那些仿真图的，能将代码发给我参考一下吗，不胜感激，谢谢！


------------------



 




------------------ 原始邮件 ------------------
发件人: "Narcissus"<notifications@github.com>;
发送时间: 2018年5月29日(星期二) 中午12:28
收件人: "NarcissusHliangZhao/Implementation_of_MEC_papers"<Implementation_of_MEC_papers@noreply.github.com>;
抄送: "陈伟健"<592922218@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [NarcissusHliangZhao/Implementation_of_MEC_papers] How tocalculate the average execution cost? (#2)




你好。
 实际上，我并没有计算average execution cost。
 LODCO算法（借助Lyapunov优化）已经将问题转变成了一个在每个time slot内的deterministic problem，没有再计算average execution cost的必要。
 如果一定要计算该值，那就按照定义来就行了：借助我设置的中间变量cost来取时均值即可。
