### ISSUE TITLE
Lemma 2

### ISSUE THREAD

**Issue by qq592922218** [NarcissusHliangZhao/Implementation_of_MEC_papers#4]
认真看了你的论文，想作为参考文献，但是对于这个Lemma 2，有点不太理解，请问能不能解释一下这个？

**Comment by qq592922218** [comment]
谢谢

**Comment by NarcissusHliangZhao** [comment]
你好。
出现了Lemma2的论文并非我所写，作者是Y. Y. Mao。Lemma2只是单纯地在分析g1(h, p) \triangleq \frac{p} {r(h,p)}这个函数的特性——即是关于p的单调增函数，且存在一个下界（这个下界可由极限理论推导得到），整个Lemma2的推导仅需使用高等数学上学期所学内容。

Lemma2的存在是为了推导出Lemma3，从而的的奥Proposition 3——也就是任务在卸载执行时的最佳传输功率。

**Comment by qq592922218** [comment]
好的，谢谢

**Comment by qq592922218** [comment]
非常感谢你的回答，我已用matla求出了这个函数的极限，与Lemma 2 的结果一致，再次感谢
